# -*- coding: utf-8 -*-
"""Copia de Analisis del Deshielo Artico con Series de Tiempo_Github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MK9KyB2rfCghr04H8K7FaEv7JHH2zeZ1
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

# 1. Simulación datos NOAA - Sea Ice Extent 1979-2024
np.random.seed(42)
years = np.arange(1979, 2025)
months = np.tile(np.arange(1, 13), len(years))
years_full = np.repeat(years, 12)

# Tendencia descendente + estacionalidad + ruido
trend = -0.05 * (years_full - 1979)
seasonal = 2 * np.sin(2 * np.pi * (months - 3) / 12)
noise = np.random.normal(0, 0.3, len(years_full))
sea_ice_extent = 15 + trend + seasonal + noise

df = pd.DataFrame({
    'year': years_full,
    'month': months,
    'sea_ice_extent': sea_ice_extent,
    'date': pd.to_datetime(years_full.astype(str) + '-' + months.astype(str) + '-01')
})

# 2. Análisis: promedio anual y tasa de cambio
df_anual = df.groupby('year')['sea_ice_extent'].mean().reset_index()
df_anual['decada'] = (df_anual['year'] // 10) * 10

# Calcular tendencia lineal
X = df_anual[['year']]
y = df_anual['sea_ice_extent']
model = LinearRegression().fit(X, y)
tendencia = model.coef_[0] * 10 # km² por década

print(f"Tasa de deshielo: {tendencia:.2f} millones km² por década")
print(f"R² Score: {model.score(X, y):.3f}")

# 3. Gráfica interactiva 1: Serie de tiempo completa
fig1 = px.line(df, x='date', y='sea_ice_extent',
               title='Extension del Hielo Marino Artico 1979-2024',
               labels={'sea_ice_extent': 'Extension (millones km²)', 'date': 'Fecha'})
fig1.add_trace(go.Scatter(x=df_anual['year'], y=model.predict(X),
                         mode='lines', name='Tendencia', line=dict(color='red', dash='dash')))
fig1.update_layout(hovermode='x unified')
fig1.write_html('serie_tiempo_interactiva.html')

# 4. Gráfica 2: Comparación por década - ARREGLADO
df['decada'] = (df['year'] // 10) * 10 # <-- Esta línea faltaba
fig2 = px.box(df, x='decada', y='sea_ice_extent',
              title='Distribucion de Hielo Marino por Decada',
              labels={'sea_ice_extent': 'Extension (millones km²)', 'decada': 'Decada'})
fig2.write_html('boxplot_decadas.html')

# 5. Gráfica 3: Mapa de calor mensual
pivot = df.pivot_table(values='sea_ice_extent', index='month', columns='year', aggfunc='mean')
fig3 = go.Figure(data=go.Heatmap(
    z=pivot.values,
    x=pivot.columns,
    y=pivot.index,
    colorscale='Blues_r',
    colorbar=dict(title='Millones km²')
))
fig3.update_layout(title='Mapa de Calor: Extension Hielo Marino por Mes y Año',
                   xaxis_title='Año', yaxis_title='Mes')
fig3.write_html('heatmap_mensual.html')

print("Graficas guardadas: serie_tiempo_interactiva.html, boxplot_decadas.html, heatmap_mensual.html")
fig1.show()
fig2.show()
fig3.show()
